<?php

declare(strict_types=1);

namespace PhpCollective\SymfonyDjot\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('symfony_djot');

        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('converters')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->booleanNode('safe_mode')
                                ->defaultTrue()
                                ->info('Enable safe mode for XSS protection (disable only for trusted content)')
                            ->end()
                            ->booleanNode('significant_newlines')
                                ->defaultFalse()
                                ->info('Allow blocks to interrupt paragraphs without blank lines (markdown-like)')
                            ->end()
                            ->scalarNode('soft_break_mode')
                                ->defaultNull()
                                ->info('How to render soft breaks: newline, space, or br')
                            ->end()
                            ->booleanNode('xhtml')
                                ->defaultFalse()
                                ->info('Output XHTML-compatible markup')
                            ->end()
                            ->arrayNode('extensions')
                                ->info('Extensions to enable for this converter')
                                ->arrayPrototype()
                                    ->beforeNormalization()
                                        ->ifString()
                                        ->then(fn ($v) => ['type' => $v])
                                    ->end()
                                    ->children()
                                        ->scalarNode('type')
                                            ->isRequired()
                                            ->info('Extension type: admonition, autolink, code_group, default_attributes, external_links, frontmatter, heading_level_shift, heading_permalinks, heading_reference, inline_footnotes, mentions, mermaid, semantic_span, smart_quotes, table_of_contents, tabs, wikilinks')
                                        ->end()
                                        // Admonition options
                                        ->arrayNode('types')
                                            ->scalarPrototype()->end()
                                            ->info('Admonition: Types to recognize (default: note, tip, warning, danger, info, success)')
                                        ->end()
                                        ->booleanNode('default_title')
                                            ->info('Admonition: Auto-generate title from type (default: true)')
                                        ->end()
                                        ->scalarNode('title_tag')
                                            ->info('Admonition: HTML tag for title (default: p)')
                                        ->end()
                                        ->scalarNode('title_class')
                                            ->info('Admonition: CSS class for title (default: admonition-title)')
                                        ->end()
                                        ->scalarNode('container_class')
                                            ->info('Admonition: CSS class for container (default: admonition)')
                                        ->end()
                                        ->variableNode('icons')
                                            ->info('Admonition: Enable icons (true for defaults, array for custom, false to disable)')
                                        ->end()
                                        ->scalarNode('icon_class')
                                            ->info('Admonition: CSS class for icon wrapper (default: admonition-icon)')
                                        ->end()
                                        // Autolink options
                                        ->arrayNode('allowed_schemes')
                                            ->scalarPrototype()->end()
                                            ->info('Autolink: URL schemes to auto-link (default: https, http, mailto)')
                                        ->end()
                                        // CodeGroup options
                                        ->scalarNode('wrapper_class')
                                            ->info('CodeGroup: CSS class for the code-group container (default: code-group)')
                                        ->end()
                                        ->scalarNode('panel_class')
                                            ->info('CodeGroup: CSS class for individual code panels (default: code-group-panel)')
                                        ->end()
                                        ->scalarNode('label_class')
                                            ->info('CodeGroup: CSS class for tab labels (default: code-group-label)')
                                        ->end()
                                        ->scalarNode('radio_class')
                                            ->info('CodeGroup: CSS class for radio inputs (default: code-group-radio)')
                                        ->end()
                                        ->scalarNode('id_prefix')
                                            ->info('CodeGroup: Prefix for generated IDs (default: codegroup)')
                                        ->end()
                                        // DefaultAttributes options
                                        ->arrayNode('defaults')
                                            ->useAttributeAsKey('node_type')
                                            ->variablePrototype()->end()
                                            ->info('DefaultAttributes: Map of node type to default attributes')
                                        ->end()
                                        // Frontmatter options
                                        ->scalarNode('default_format')
                                            ->info('Frontmatter: Default format (yaml, toml, json)')
                                        ->end()
                                        ->booleanNode('render_as_comment')
                                            ->info('Frontmatter: Render frontmatter as HTML comment')
                                        ->end()
                                        // External links options
                                        ->arrayNode('internal_hosts')
                                            ->scalarPrototype()->end()
                                            ->info('ExternalLinks: Hosts to treat as internal')
                                        ->end()
                                        ->scalarNode('target')
                                            ->info('ExternalLinks: Target attribute (default: _blank)')
                                        ->end()
                                        ->scalarNode('rel')
                                            ->info('ExternalLinks: Rel attribute (default: noopener noreferrer)')
                                        ->end()
                                        ->booleanNode('nofollow')
                                            ->info('ExternalLinks: Add nofollow to rel')
                                        ->end()
                                        // Heading permalinks options
                                        ->scalarNode('symbol')
                                            ->info('HeadingPermalinks: Link symbol (default: #)')
                                        ->end()
                                        ->scalarNode('position')
                                            ->info('HeadingPermalinks: Position - before or after (default: after)')
                                        ->end()
                                        ->scalarNode('class')
                                            ->info('HeadingPermalinks: CSS class for the link')
                                        ->end()
                                        ->scalarNode('aria_label')
                                            ->info('HeadingPermalinks: Aria label for accessibility')
                                        ->end()
                                        // Mentions options
                                        ->scalarNode('user_url_template')
                                            ->info('Mentions: URL template for @mentions (use {username} placeholder)')
                                        ->end()
                                        ->scalarNode('user_class')
                                            ->info('Mentions: CSS class for mention links')
                                        ->end()
                                        // Smart quotes options
                                        ->scalarNode('locale')
                                            ->info('SmartQuotes: Locale for quote styles (default: en)')
                                        ->end()
                                        // Table of contents options
                                        ->integerNode('min_level')
                                            ->info('TableOfContents: Minimum heading level (default: 1)')
                                        ->end()
                                        ->integerNode('max_level')
                                            ->info('TableOfContents: Maximum heading level (default: 6)')
                                        ->end()
                                        ->scalarNode('toc_class')
                                            ->info('TableOfContents: CSS class for the TOC container')
                                        ->end()
                                        // Wikilinks options
                                        ->scalarNode('url_template')
                                            ->info('Wikilinks: URL template (use {page} placeholder)')
                                        ->end()
                                        ->scalarNode('link_class')
                                            ->info('Wikilinks: CSS class for wiki links')
                                        ->end()
                                        // HeadingLevelShift options
                                        ->integerNode('shift')
                                            ->info('HeadingLevelShift: Number of levels to shift (1-5)')
                                        ->end()
                                        // HeadingReference options
                                        ->scalarNode('css_class')
                                            ->info('HeadingReference/InlineFootnotes/Mermaid: CSS class')
                                        ->end()
                                        // Mermaid options
                                        ->scalarNode('tag')
                                            ->info('Mermaid: HTML tag to use (pre or div)')
                                        ->end()
                                        ->booleanNode('wrap_in_figure')
                                            ->info('Mermaid: Wrap in figure element')
                                        ->end()
                                        ->scalarNode('figure_class')
                                            ->info('Mermaid: CSS class for figure element')
                                        ->end()
                                        // Tabs options
                                        ->scalarNode('mode')
                                            ->info('Tabs: Output mode (css or aria)')
                                        ->end()
                                        ->scalarNode('tab_class')
                                            ->info('Tabs: CSS class for tab panels')
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                    ->defaultValue([
                        'default' => [
                            'safe_mode' => true,
                            'extensions' => [],
                        ],
                    ])
                ->end()
                ->arrayNode('cache')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable caching of rendered output')
                        ->end()
                        ->scalarNode('pool')
                            ->defaultValue('cache.app')
                            ->info('Cache pool service to use')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
